/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Tanpa autentikasi. 200 untuk `ok`/`degraded`, 503 untuk `down`/`shutting_down`. Tidak berisi data sensitif. Bukan bagian dari versi API v1.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Email + password -> access token (JWT, ±15 menit) dan refresh token (opaque, 30 hari, sekali pakai). Batas: 10 percobaan/15 menit per akun dan 30 per IP (429 + Retry-After). Kode khusus: INVALID_CREDENTIALS (401), ACCOUNT_EXPIRED (403).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Perbarui token (rotasi)
         * @description Menukar refresh token dengan pasangan baru; refresh token lama LANGSUNG tidak berlaku. Memakai refresh token yang sudah pernah dipakai (REFRESH_REUSED) mencabut SELURUH sesi perangkat itu. Kode 401: INVALID_REFRESH_TOKEN, REFRESH_EXPIRED, REFRESH_REVOKED, REFRESH_REUSED, SESSION_REVOKED — untuk semuanya: hapus token lokal dan minta login ulang. Lakukan refresh dengan SATU permintaan sekaligus (single-flight).
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout perangkat ini
         * @description Mencabut sesi (seluruh rantai refresh token) perangkat ini. Selalu 204 (idempoten). Access token yang sudah terbit tetap berlaku sampai kedaluwarsa (≤ 15 menit): buang dari memori di klien.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout dari semua perangkat
         * @description Mencabut semua refresh token user dan menaikkan tokenVersion: SEMUA access token (mobile) dan sesi cookie (web) berhenti berlaku seketika.
         */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil user saat ini */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar device
         * @description Device yang bisa diakses (owner atau collaborator), terbaru dulu, cursor pagination (`nextCursor` -> `?cursor=`). `view=summary` (default) menyertakan ringkasan telemetri per pack (tegangan, arus, daya, suhu, delta cell). `online`: ada data dalam 180 detik terakhir. Mendukung ETag/If-None-Match.
         */
        get: operations["listDevices"];
        put?: never;
        /**
         * Daftarkan / klaim device
         * @description Mendaftarkan device dengan `serialNumber` (ID/lisensi fisik; huruf, angka, `.`, `-`, `_`, maks 64). Device baru `verified=false` sampai admin menyetujui. Bila serial itu sudah pernah mengirim data dan belum dimiliki siapa pun, device itu diklaim beserta riwayatnya. 409 DEVICE_ALREADY_CLAIMED bila sudah punya owner. Batas: 20 klaim/jam per user.
         */
        post: operations["claimDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail device (snapshot)
         * @description Snapshot terbaru semua pack dan cell + ringkasan + collaborator. Email collaborator hanya terlihat oleh OWNER. User yang bukan anggota device mendapat 404 (bukan 403). Mendukung ETag/If-None-Match.
         */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /**
         * Lepas (unclaim) atau hapus device
         * @description Hanya owner. `mode=unclaim` (default): melepas kepemilikan — data tetap, nama dikosongkan, `verified` kembali false, semua collaborator dilepas. `mode=delete`: hapus permanen device + seluruh riwayat; wajib `confirmSerial` = serialNumber. Perangkat yang masih mengirim data akan muncul lagi sebagai device baru tanpa owner.
         */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        /**
         * Ubah nama device
         * @description Owner atau editor.
         */
        patch: operations["updateDevice"];
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ringkasan lintas device
         * @description Jumlah device (online/offline/menunggu verifikasi), total daya, suhu maksimum, delta cell maksimum — dihitung dari device ONLINE saja. Tanpa SoC/SoH. Mendukung ETag/If-None-Match (generatedAt tidak ikut hash).
         */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Riwayat telemetri (time-series)
         * @description Seri per pack (`temperature` °C, `current` A, `power` W) atau per cell (`voltage` V). Default: 24 jam terakhir, bucket 5m, metrics temperature,current,power.
         *
         *     - `bucket=raw`: sampel asli; rentang maks 48 jam; `voltage` tidak boleh digabung dengan metrik pack; halaman berikutnya lewat `nextCursor` → `?cursor=`.
         *     - `bucket=1m|5m|1h`: agregat (v = rata-rata, min, max) dihitung di database; total titik dibatasi ~20.000 (lebih dari itu → 400 VALIDATION_ERROR dengan saran bucket/rentang).
         *     - Data lebih tua dari 30 hari hanya ada sebagai agregat (rollup 1 menit), bucket tetap 1m/5m/1h.
         *     - Bucket tanpa sampel tidak muncul; titik null dibuang; `temperature` null (sensor error) tidak muncul sebagai titik.
         *     Mendukung ETag/If-None-Match.
         */
        get: operations["getDeviceHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/collaborators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daftar collaborator
         * @description Semua anggota boleh melihat; `email` hanya terisi untuk OWNER (selain itu null).
         */
        get: operations["listCollaborators"];
        put?: never;
        /**
         * Undang collaborator
         * @description Hanya owner. Mengundang user terdaftar lewat email sebagai `viewer` (default) atau `editor`. Kode: USER_NOT_FOUND (404), ALREADY_COLLABORATOR (409). Batas: 30 undangan/jam per user (mencegah enumerasi email).
         */
        post: operations["addCollaborator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/collaborators/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cabut collaborator / keluar
         * @description Owner mencabut siapa pun; collaborator boleh keluar sendiri (userId = dirinya). Selain itu 403. COLLABORATOR_NOT_FOUND (404) bila bukan anggota.
         */
        delete: operations["removeCollaborator"];
        options?: never;
        head?: never;
        /**
         * Ubah peran collaborator
         * @description Hanya owner.
         */
        patch: operations["updateCollaborator"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded" | "down" | "shutting_down";
            uptimeSec: number;
            db: {
                ok: boolean;
                latencyMs: number | null;
            };
            mqtt: {
                connected: boolean;
                /**
                 * Format: date-time
                 * @example 2026-09-21T08:15:00.000Z
                 */
                lastMessageAt: string | null;
                lastMessageAgeSec: number | null;
            };
            ingest: {
                queueDepth: number;
            };
            counters: {
                [key: string]: number;
            };
        };
        ErrorResponse: {
            error: {
                /**
                 * @description Kode stabil untuk mesin; jangan mem-branch pada `message`.
                 * @example DEVICE_NOT_FOUND
                 */
                code: string;
                /** @description Pesan untuk manusia (bahasa Indonesia). */
                message: string;
                /** @description Hanya untuk VALIDATION_ERROR: daftar isu per field. */
                details?: components["schemas"]["ErrorIssue"][];
            };
            /** @description Sama dengan header X-Request-Id; sertakan saat melaporkan masalah. */
            requestId: string;
        };
        ErrorIssue: {
            path: string;
            message: string;
        };
        TokenResponse: {
            /** @description JWT, kirim sebagai `Authorization: Bearer …`. Simpan HANYA di memori. */
            accessToken: string;
            /** @description Opaque, sekali pakai (rotasi). Simpan di Keychain/Keystore. */
            refreshToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /**
             * @description Umur access token dalam detik.
             * @example 900
             */
            expiresIn: number;
            /**
             * @description Umur refresh token dalam detik.
             * @example 2592000
             */
            refreshExpiresIn: number;
            user: components["schemas"]["Me"];
        };
        Me: {
            id: string;
            email: string;
            name: string | null;
            role: components["schemas"]["UserRole"];
            /**
             * Format: date-time
             * @description Akun berakhir pada waktu ini; null = tidak pernah.
             * @example 2026-09-21T08:15:00.000Z
             */
            expiresAt: string | null;
        };
        /** @enum {string} */
        UserRole: "USER" | "ADMIN";
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** @description Nama perangkat (mis. 'Pixel 8'), ditampilkan di daftar sesi. */
            deviceName?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        DeviceListResponse: {
            items: components["schemas"]["DeviceListItem"][];
            /** @description Kirim sebagai ?cursor= untuk halaman berikutnya; null = habis. */
            nextCursor: string | null;
        };
        DeviceListItem: {
            id: string;
            serialNumber: string;
            name: string | null;
            /** @description Sudah disetujui admin. */
            verified: boolean;
            role: components["schemas"]["DeviceRole"];
            owner: components["schemas"]["DeviceOwner"];
            /** @description Ada data dalam batas waktu online (default 180 dtk). */
            online: boolean;
            /**
             * Format: date-time
             * @description Waktu server menerima data terakhir.
             * @example 2026-09-21T08:15:00.000Z
             */
            lastSeenAt: string | null;
            packCount: number;
            summary?: components["schemas"]["DeviceStats"];
        };
        /**
         * @description Peran user yang sedang login pada device ini.
         * @enum {string}
         */
        DeviceRole: "owner" | "editor" | "viewer";
        DeviceOwner: {
            id: string;
            name: string | null;
        };
        /** @description Ada bila view=summary. */
        DeviceStats: {
            packs: components["schemas"]["PackSummary"][];
            maxTemperatureC: number | null;
            maxCellDeltaMv: number | null;
            totalPowerW: number | null;
            minCellVoltageV: number | null;
            maxCellVoltageV: number | null;
        };
        PackSummary: {
            index: number;
            /** @description Jumlah tegangan seluruh cell pack (V). */
            voltageV: number | null;
            /** @description Ampere; NEGATIF = charging, positif = discharging. */
            currentA: number | null;
            powerW: number | null;
            /** @description null = sensor error / tidak ada pembacaan. */
            temperatureC: number | null;
            /** @description Selisih cell tertinggi − terendah (mV). */
            cellDeltaMv: number | null;
            cellCount: number;
        };
        DeviceDetail: {
            id: string;
            serialNumber: string;
            name: string | null;
            /** @description Sudah disetujui admin. */
            verified: boolean;
            role: components["schemas"]["DeviceRole"];
            owner: components["schemas"]["DeviceOwner"];
            /** @description Ada data dalam batas waktu online (default 180 dtk). */
            online: boolean;
            /**
             * Format: date-time
             * @description Waktu server menerima data terakhir.
             * @example 2026-09-21T08:15:00.000Z
             */
            lastSeenAt: string | null;
            packCount: number;
            /**
             * Format: date-time
             * @example 2026-09-21T08:15:00.000Z
             */
            createdAt: string;
            summary: components["schemas"]["DeviceStats"];
            packs: components["schemas"]["PackDetail"][];
            collaborators: components["schemas"]["Collaborator"][];
        };
        PackDetail: {
            index: number;
            temperatureC: number | null;
            balancerConnected: boolean;
            currentA: number | null;
            powerW: number | null;
            voltageV: number | null;
            cellDeltaMv: number | null;
            /**
             * Format: date-time
             * @description Waktu efektif data (jam device bila wajar, selain itu waktu server).
             * @example 2026-09-21T08:15:00.000Z
             */
            recordedAt: string | null;
            /**
             * Format: date-time
             * @description Waktu server menerima data.
             * @example 2026-09-21T08:15:00.000Z
             */
            receivedAt: string | null;
            cells: components["schemas"]["Cell"][];
        };
        Cell: {
            index: number;
            voltageV: number;
        };
        Collaborator: {
            userId: string;
            name: string | null;
            /** @description Hanya terisi bila peminta adalah OWNER device; selain itu null. */
            email: string | null;
            role: components["schemas"]["CollaboratorRole"];
            /**
             * Format: date-time
             * @example 2026-09-21T08:15:00.000Z
             */
            addedAt: string;
        };
        /** @enum {string} */
        CollaboratorRole: "viewer" | "editor";
        DashboardSummary: {
            deviceCount: number;
            onlineCount: number;
            offlineCount: number;
            pendingVerificationCount: number;
            /** @description Jumlah daya pack pada device ONLINE; negatif = net charging. */
            totalPowerW: number | null;
            maxTemperatureC: number | null;
            maxCellDeltaMv: number | null;
            /**
             * Format: date-time
             * @example 2026-09-21T08:15:00.000Z
             */
            generatedAt: string;
        };
        HistoryResponse: {
            deviceId: string;
            /**
             * Format: date-time
             * @example 2026-09-21T08:15:00.000Z
             */
            from: string;
            /**
             * Format: date-time
             * @example 2026-09-21T08:15:00.000Z
             */
            to: string;
            bucket: components["schemas"]["HistoryBucket"];
            series: components["schemas"]["HistorySeries"][];
            /** @description Hanya untuk bucket=raw; null = habis. */
            nextCursor: string | null;
        };
        /** @enum {string} */
        HistoryBucket: "raw" | "1m" | "5m" | "1h";
        HistorySeries: {
            /** @enum {string} */
            scope: "pack" | "cell";
            packIndex: number;
            /** @description null untuk seri level pack. */
            cellIndex: number | null;
            metric: components["schemas"]["HistoryMetric"];
            /** @enum {string} */
            unit: "C" | "A" | "W" | "V";
            points: components["schemas"]["HistoryPoint"][];
        };
        /** @enum {string} */
        HistoryMetric: "temperature" | "current" | "power" | "voltage";
        HistoryPoint: {
            /**
             * Format: date-time
             * @description Awal bucket (UTC). Untuk raw: waktu sampel.
             * @example 2026-09-21T08:15:00.000Z
             */
            t: string;
            /** @description Nilai (raw) atau rata-rata bucket. */
            v: number;
            /** @description Minimum bucket; null untuk raw. */
            min: number | null;
            /** @description Maksimum bucket; null untuk raw. */
            max: number | null;
        };
        ClaimDeviceRequest: {
            serialNumber: string;
            name?: string;
        };
        UpdateDeviceRequest: {
            name: string;
        };
        CollaboratorList: {
            items: components["schemas"]["Collaborator"][];
        };
        AddCollaboratorRequest: {
            /** Format: email */
            email: string;
            role?: components["schemas"]["CollaboratorRole"];
        };
        UpdateCollaboratorRequest: {
            role: components["schemas"]["CollaboratorRole"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DB hidup (MQTT mungkin terputus = degraded) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token diterbitkan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description FORBIDDEN: tidak punya hak pada resource ini */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: tunggu sesuai header Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Pasangan token baru */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description FORBIDDEN: tidak punya hak pada resource ini */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: tunggu sesuai header Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Sesi dicabut */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: tunggu sesuai header Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Semua sesi dicabut */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil */
            200: {
                headers: {
                    /** @description Validator. Kirim balik sebagai If-None-Match pada permintaan berikutnya. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Tidak berubah sejak ETag pada If-None-Match; tidak ada body. Pakai salinan lokal. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /** @description `summary` menyertakan ringkasan telemetri per device. */
                view?: "basic" | "summary";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Satu halaman device */
            200: {
                headers: {
                    /** @description Validator. Kirim balik sebagai If-None-Match pada permintaan berikutnya. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
            /** @description Tidak berubah sejak ETag pada If-None-Match; tidak ada body. Pakai salinan lokal. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    claimDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimDeviceRequest"];
            };
        };
        responses: {
            /** @description Device milik Anda */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description CONFLICT: bentrok dengan keadaan saat ini */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: tunggu sesuai header Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID device (bukan serialNumber). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail device */
            200: {
                headers: {
                    /** @description Validator. Kirim balik sebagai If-None-Match pada permintaan berikutnya. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description Tidak berubah sejak ETag pada If-None-Match; tidak ada body. Pakai salinan lokal. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDevice: {
        parameters: {
            query?: {
                /** @description `unclaim`: lepas kepemilikan (data tetap, device kembali tanpa owner, collaborator dilepas). `delete`: hapus device + seluruh riwayat (wajib confirmSerial). */
                mode?: "unclaim" | "delete";
                /** @description Wajib = serialNumber bila mode=delete. */
                confirmSerial?: string;
            };
            header?: never;
            path: {
                /** @description ID device (bukan serialNumber). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Selesai */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description FORBIDDEN: tidak punya hak pada resource ini */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID device (bukan serialNumber). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeviceRequest"];
            };
        };
        responses: {
            /** @description Device setelah diubah */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description FORBIDDEN: tidak punya hak pada resource ini */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ringkasan */
            200: {
                headers: {
                    /** @description Validator. Kirim balik sebagai If-None-Match pada permintaan berikutnya. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Tidak berubah sejak ETag pada If-None-Match; tidak ada body. Pakai salinan lokal. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDeviceHistory: {
        parameters: {
            query?: {
                /** @description ISO-8601 UTC; default = to − 24 jam. */
                from?: string;
                /** @description ISO-8601 UTC; default = sekarang. */
                to?: string;
                bucket?: components["schemas"]["HistoryBucket"];
                /** @description CSV dari temperature,current,power,voltage. Default: temperature,current,power. `voltage` = per cell (banyak seri). */
                metrics?: string;
                /** @description Batasi ke satu pack. */
                packIndex?: number | null;
                cursor?: string;
                /** @description Hanya untuk raw: maks sampel per halaman (default 1000). */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description ID device (bukan serialNumber). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seri waktu */
            200: {
                headers: {
                    /** @description Validator. Kirim balik sebagai If-None-Match pada permintaan berikutnya. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Tidak berubah sejak ETag pada If-None-Match; tidak ada body. Pakai salinan lokal. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCollaborators: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID device (bukan serialNumber). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collaborator */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollaboratorList"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addCollaborator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID device (bukan serialNumber). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCollaboratorRequest"];
            };
        };
        responses: {
            /** @description Collaborator ditambahkan */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collaborator"];
                };
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description FORBIDDEN: tidak punya hak pada resource ini */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description CONFLICT: bentrok dengan keadaan saat ini */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RATE_LIMITED: tunggu sesuai header Retry-After */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeCollaborator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID device. */
                id: string;
                /** @description ID user collaborator. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dicabut */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description FORBIDDEN: tidak punya hak pada resource ini */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCollaborator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID device. */
                id: string;
                /** @description ID user collaborator. */
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCollaboratorRequest"];
            };
        };
        responses: {
            /** @description Collaborator setelah diubah */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Collaborator"];
                };
            };
            /** @description VALIDATION_ERROR / INVALID_JSON: request tidak valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description UNAUTHORIZED: token hilang/kedaluwarsa/dicabut (atau kredensial salah) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description FORBIDDEN: tidak punya hak pada resource ini */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description NOT_FOUND: resource tidak ada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description INTERNAL: kesalahan server (sertakan requestId saat melapor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
